### ISSUE TITLE
SSO credential log out happens too frequently

### ISSUE THREAD

**Issue by jasonford** [knowlearning/platform#26]
Seen on all sites, but one bug report in anothe repo so far: https://github.com/pila-project/pila-platform/issues/164

**Comment by OECDPILA** [comment]
![Screenshot](https://github.com/knowlearning/platform/assets/145113767/55c5541c-6394-44e5-85d6-de19621c8580)
![screenshot3](https://github.com/knowlearning/platform/assets/145113767/c9188305-c3c9-458d-a696-ca1ca2dbdd45)
![screenshot2](https://github.com/knowlearning/platform/assets/145113767/baf70a53-ec19-4428-b3ac-75573ada81c0)

Here are some screenshots of the bug for context. I am not sure if it is the SSO credential that logs out too frequently, but rather they could not access their account at all because it kept bringing them back to the SSO before showing their teacher account.
